[package]
name = "split-range"
version = "0.0.1-dev"
authors = ["Mikhail Zabaluev <mikhail.zabaluev@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
bytes = { version = "0.4", optional = true }
