[package]
name = "range-split"
version = "0.0.1-dev"
authors = ["Mikhail Zabaluev <mikhail.zabaluev@gmail.com>"]
edition = "2018"

[features]
default = ["bytes"]

[dependencies]
bytes = { version = "0.4", optional = true }
